version: "3.9"

services:

  # ======================
  # BASES DE DATOS
  # ======================

  db_camiones:
    image: postgres:15
    container_name: db_camiones
    restart: always
    environment:
      POSTGRES_DB: db_camiones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - db_camiones_data:/var/lib/postgresql/data

  servicio-camiones:
    build: ./servicio-camiones
    container_name: servicio-camiones
    depends_on:
      - db_camiones
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_camiones:5432/db_camiones
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  # ------------------------ CONTENEDORES ------------------------
  db_contenedores:
    image: postgres:15
    container_name: db_contenedores
    restart: always
    environment:
      POSTGRES_DB: db_contenedores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5434:5432"
    volumes:
      - db_contenedores_data:/var/lib/postgresql/data

  servicio-contenedores:
    build: ./servicio-contenedores
    container_name: servicio-contenedores
    depends_on:
      - db_contenedores
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_contenedores:5432/db_contenedores
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  # ------------------------ SOLICITUDES ------------------------
  db_solicitudes:
    image: postgres:15
    container_name: db_solicitudes
    restart: always
    environment:
      POSTGRES_DB: db_solicitudes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5435:5432"
    volumes:
      - db_solicitudes_data:/var/lib/postgresql/data
  servicio-solicitudes:
    build: ./servicio-solicitudes
    container_name: servicio-solicitudes
    depends_on:
      - db_solicitudes
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_solicitudes:5432/db_solicitudes?options=-c%20TimeZone=America/Argentina/Buenos_Aires
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  # ------------------------ TARIFAS ------------------------
  db_tarifas:
    image: postgres:15
    container_name: db_tarifas
    restart: always
    environment:
      POSTGRES_DB: db_tarifas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5436:5432"
    volumes:
      - db_tarifas_data:/var/lib/postgresql/data
  servicio-tarifas:
    build: ./servicio-tarifas
    container_name: servicio-tarifas
    depends_on:
      - db_tarifas
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_tarifas:5432/db_tarifas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


  # ------------------------ TRAMOS / RUTAS ------------------------
  db_tramos_rutas:
    image: postgres:15
    container_name: db_tramos_rutas
    restart: always
    environment:
      POSTGRES_DB: db_tramos_rutas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
    ports:
      - "5439:5432"
    volumes:
      - db_tramos_rutas_data:/var/lib/postgresql/data

  # ------------------------ USUARIOS ------------------------
  db_usuarios:
    image: postgres:15
    container_name: db_usuarios
    restart: always
    environment:
      POSTGRES_DB: db_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5438:5432"
    volumes:
      - db_usuarios_data:/var/lib/postgresql/data

  # ======================
  # AUTENTICACIÃ“N
  # ======================

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db_usuarios:5432/db_usuarios
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db_usuarios

  # ======================
  # OSRM (MAPAS Y RUTEO)
  # ======================

  # ------------------------ OSRM ------------------------
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed /data/argentina-latest.osrm
    restart: unless-stopped

# ======================
# VOLUMENES
# ======================

# ------------------------ VOLUMES ------------------------
volumes:
  db_camiones_data:
  db_contenedores_data:
  db_solicitudes_data:
  db_tarifas_data:
  db_tramos_rutas_data:
  db_usuarios_data:
  osrm-data:
